# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code for South Africa
email: info@code4sa.org
description: > # this means to ignore newlines until "baseurl:"
  Code for South Africa is a civic technology lab that uses data and technology to drive social change

collections:
  projects:
    output: true
  our-team:
    output: true

gems: [jekyll-paginate, algoliasearch-jekyll]

paginate: 5
paginate_path: "/posts/page:num"