# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code for South Africa
email: info@code4sa.org
description: Code for South Africa is a civic technology lab that uses data and technology to drive social change
url: http://code4sa.org

collections:
  projects:
    output: true
  our-team:
    output: true

defaults:
  -
    scope:
      type: "posts"
      scope: "_posts/"
    values:
      type: "posts"

paginate: 5
paginate_path: "/blog/page:num"
